### PR TITLE
remove hidden characters

### PR DESCRIPTION
**Pull request by letsgetrandy**
There were a couple of hidden characters in here causing me errors in Chrome.

I've removed them.

### CODE REVIEW

**Comment by marbemac** [comment]
+1

**Comment by christianalfoni** [comment]
Okay, pushed this now. Will release new version very soon :-)

Btw, how do I avoid these hidden chars? Or at least identify them?

**Comment by marbemac** [comment]
@christianalfoni What I'd suggest is installing the Highlighter sublime plugin, and then adding this to the user settings for that plugin:

```
{
    "highlighter_regex": "(\t+ +)|( +\t+)|[^\\x00-\\x7F]|[\u2026\u2018\u2019\u201c\u201d\u2013\u2014]|[\t ]+$"
}
```

That'll highlight these sorts of annoying hidden ascii characters, for easy removal.

**Comment by marbemac** [comment]
You can also actually see them if you go to File > Reopen with encoding > ISO 8859-1.

**Pull request merged**
